name: SuperCoolComposeStack
services:
  api:
    image: mysupercoolapp:somefancytag
    build: .
    env_file: .env
    environment:
      - DATABASE_URL=mongodb://mongo:27017/mycoolappdatabase
    ports:
      - 5432:3001
      - 65535:3001
      - 1025:3001
  mongo: 
    image: mongo
    ports:
      - 54321:27017
    volumes: 
      # - ./mongodbdata:/data/db
      - mongodb-data:/data/db


# Using volumes like this stored the data in a Docker-managed location, typically a hidden folder.
#  e.g. \\wsl$\docker-desktop-data\data\docker\volumes on Windows
#  or   /var/lib/docker/volumes on Linux-based systems
volumes:
  mongodb-data:
    driver: local